"use client";
import { useState } from "react";
import { motion } from "framer-motion";
import { ArrowUpRight } from "lucide-react";
import { FaGithub, FaLinkedinIn } from "react-icons/fa";
import { projects } from "../data/projects";
type Panel = "about" | "projects" | "experience" | "skills" | "contact";
const tabs: { id: Panel; label: string }[] = [{ id: "about", label: "About" }, { id: "projects", label: "Projects" }, { id: "experience", label: "Experience" }, { id: "skills", label: "Skills" }, { id: "contact", label: "Contact" }];
export default function Portfolio() { const [active, setActive] = useState<Panel>("about"); const [darkMode, setDarkMode] = useState(false); return <main className={`canvas${darkMode ? " dark-mode" : ""}`}><aside className="identity"><div className="identity-copy"><h1>Fatima<br /><em>Alfurais</em></h1></div></aside><section className="workspace" aria-label="Portfolio content"><header className="workspace-header"><p><b>{tabs.find(tab => tab.id === active)?.label}</b></p><button className="theme-toggle" onClick={() => setDarkMode(value => !value)}>{darkMode ? "Light" : "Dark"}</button></header><nav className="tabbar" aria-label="Portfolio sections">{tabs.map(tab => <button key={tab.id} onClick={() => setActive(tab.id)} className={active === tab.id ? "active" : ""}>{tab.label}</button>)}</nav><motion.div className="panel" key={active} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.35, ease: "easeOut" }}>{active === "about" && <About />}{active === "projects" && <Projects />}{active === "experience" && <Experience />}{active === "skills" && <Skills />}{active === "contact" && <Contact />}</motion.div></section></main>; }
function About() { return <div className="about-panel"><div><p className="about-statement"><strong>I am a software engineering student</strong><span>interested in artificial intelligence, full-stack development, and practical applications of machine learning.</span></p></div><div className="note"><span>Currently learning</span><strong>How to build reliable AI-powered applications.</strong><p>React &middot; Next.js &middot; Python &middot; FastAPI &middot; TensorFlow</p></div></div>; }
function Projects() { return <div className="projects-panel"><div className="panel-title"><div><h2>Things I&apos;ve made.</h2></div><span>{projects.length} projects</span></div><div className="project-stack">{projects.map(project => <a className="mini-project" key={project.name} href={project.url} target="_blank" rel="noreferrer"><div className="project-thumb">{project.image ? <img src={project.image} alt={`${project.name} preview`} /> : <span>Preview<br />soon</span>}</div><div><h3>{project.name}</h3><p className="project-description">{project.desc}</p><p className="project-tech">{project.type} &middot; {project.tech.slice(0, 2).join(" / ")}</p></div><ArrowUpRight className="link-icon" aria-hidden="true" /></a>)}</div></div>; }
function Experience() { const roles = [{ title: "AI & Cybersecurity Intern", company: "EARTech", date: "Aug 2026 – Present", place: "Remote", detail: "Building practical foundations across AI systems and cybersecurity.", skills: ["AI", "Cybersecurity"], tone: "one" }, { title: "Software Engineering Intern", company: "Synergy Maze AI", date: "Jul 2026 – Present", place: "On-site", detail: "Supporting software development work in an AI-focused team environment.", skills: ["Software", "AI"], tone: "two" }, { title: "Software Engineering Intern", company: "Ebtekar Raqmi", date: "Dec 2025 – May 2026", place: "Remote", detail: "Contributed to data analysis, visualization, and model-related development workflows.", skills: ["Machine Learning", "React"], tone: "three" }, { title: "Artificial Intelligence Intern", company: "BLUESENSE", date: "Oct 2025 – Nov 2025", place: "Remote", detail: "Completed an AI internship centered on practical machine-learning foundations.", skills: ["AI", "Machine Learning"], tone: "four" }]; return <div className="experience-panel"><div className="panel-title"><h2>Places I&apos;ve<br /><span>grown.</span></h2><span>{roles.length} chapters</span></div><div className="experience-list">{roles.map(role => <article className={`experience-item experience-${role.tone}`} key={role.company}><div><h3>{role.title}</h3><p className="experience-company">{role.company}</p><p className="experience-meta">{role.date}</p><p className="experience-detail">{role.detail}</p><div className="experience-tags">{role.skills.map(skill => <span key={skill}>{skill}</span>)}</div><span className="experience-place">{role.place}</span></div></article>)}</div></div>; }
function Skills() { const skills = ["React", "Next.js", "TypeScript", "Python", "FastAPI", "TensorFlow", "OpenCV", "SQL", "Git", "Docker", "Figma", "scikit-learn"]; return <div className="skills-panel"><div><h2>My working<br />toolkit.</h2></div><div className="skill-cloud">{skills.map((skill, index) => <span className={`skill skill-${index % 4}`} key={skill}>{skill}</span>)}</div></div>; }
function Contact() { return <div className="contact-panel"><div><h2>Let&apos;s talk<br />about <span>your idea.</span></h2></div><div className="contact-actions"><a href="mailto:alfuraisf@gmail.com">alfuraisf@gmail.com <ArrowUpRight className="link-icon" aria-hidden="true" /></a><div className="social-links"><a href="https://www.linkedin.com/in/fatima-alfurais?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app" target="_blank" rel="noreferrer"><FaLinkedinIn className="brand-icon" aria-hidden="true" />LinkedIn <ArrowUpRight className="link-icon" aria-hidden="true" /></a><a href="https://github.com/fatima448" target="_blank" rel="noreferrer"><FaGithub className="brand-icon github" aria-hidden="true" />GitHub <ArrowUpRight className="link-icon" aria-hidden="true" /></a></div><p>Open to internships, entry-level roles, and project collaboration.</p></div></div>; }
