"use client";
/* eslint-disable react/jsx-no-comment-textnodes */
import Image from "next/image";import{motion,AnimatePresence}from"framer-motion";import{useState}from"react";import{projects}from"./data/projects";
const sections=["Home","About Me","Projects","Skills","Experience","Contact"] as const;type Section=typeof sections[number];
export default function Home(){const[active,setActive]=useState<Section>("Home"),[filter,setFilter]=useState("All");const shown=filter==="All"?projects:projects.filter(p=>p.type===filter);return <main className="shell"><div className="app"><header><a className="mark" onClick={()=>setActive("Home")}>FA<span>•</span></a><nav>{sections.map(s=><button className={active===s?"on":""} onClick={()=>setActive(s)} key={s}>{s}</button>)}</nav><span className="online">● AVAILABLE</span></header><section className="viewport"><AnimatePresence mode="wait"><motion.div key={active} className="view" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} transition={{duration:.28}}>{active==="Home"&&<HomeView go={setActive}/>} {active==="About Me"&&<About/>}{active==="Projects"&&<Projects filter={filter} setFilter={setFilter} list={shown}/>} {active==="Skills"&&<Skills/>}{active==="Experience"&&<Experience/>}{active==="Contact"&&<Contact/>}</motion.div></AnimatePresence><motion.div className="guide" animate={{y:[0,-7,0],rotate:[0,.7,0]}} transition={{repeat:Infinity,duration:4,ease:"easeInOut"}}><Image src="/mascot-guide.png" alt="Chibi software engineer guide mascot" width={1024} height={1024}/></motion.div></section><footer><span>workspace / fatima alfurais</span><span>{active.toLowerCase()}_view</span></footer></div></main>}
function HomeView({go}:{go:(s:Section)=>void}){return <div className="home"><p className="eyebrow">// SOFTWARE ENGINEER · SAUDI ARABIA</p><h1>Designing systems<br/>with <em>clarity.</em></h1><p>I&apos;m Fatima, a software engineering student exploring intelligent products, robust backends, and thoughtful interfaces.</p><button className="cta" onClick={()=>go("Projects")}>Explore work ↗</button><div className="signal">&lt;/&gt; currently building useful things</div></div>}
function About(){return <div className="split"><div><p className="eyebrow">01 / ABOUT ME</p><h2>Curious by nature.<br/><em>Precise by practice.</em></h2></div><div className="copy"><p>I build at the point where people, ideas, and software systems meet. I enjoy making difficult things feel understandable.</p><p>My interests span AI, machine learning, computer vision, backend engineering, and products with a reason to exist.</p><div className="chips"><span>AI systems</span><span>Product thinking</span><span>Scalable backend</span></div></div></div>}
function Projects({filter,setFilter,list}:{filter:string;setFilter:(x:string)=>void;list:typeof projects}){const cats=["All","Frontend","Full Stack","Backend","Artificial Intelligence","Machine Learning"];return <div><p className="eyebrow">02 / PROJECTS</p><h2>Selected <em>experiments.</em></h2><div className="filters">{cats.map(c=><button className={filter===c?"on":""} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="cards">{list.map(p=><article key={p.name}><span>{p.type}</span><h3>{p.name}</h3><p>{p.desc}</p><small>{p.tech.join(" · ")}</small><footer>{p.features}<b>GitHub ↗</b></footer></article>)}</div></div>}
function Skills(){return <div><p className="eyebrow">03 / SKILLS</p><h2>A toolkit for<br/><em>thoughtful building.</em></h2><div className="skillgrid">{[["Frontend","React · Next.js · TypeScript"],["Backend","Node · APIs · FastAPI"],["Data","PostgreSQL · SQL"],["AI / ML","Python · TensorFlow · OpenCV"],["Tools","Git · Docker · Figma"],["DevOps","CI/CD · Cloud fundamentals"]].map(([a,b])=><div key={a}><i>✦</i><h3>{a}</h3><p>{b}</p></div>)}</div></div>}
function Experience(){return <div><p className="eyebrow">04 / EXPERIENCE</p><h2>Learning in<br/><em>public.</em></h2><div className="timeline"><article><span>NOW</span><h3>Software Engineering Student</h3><p>Growing foundations across software, intelligent systems, and product design.</p></article><article><span>NEXT</span><h3>Thoughtful collaborations</h3><p>Seeking internships and teams where careful engineering creates real value.</p></article></div></div>}
function Contact(){return <div className="contact"><p className="eyebrow">05 / CONTACT</p><h2>Let&apos;s build<br/><em>something useful.</em></h2><a href="mailto:hello@fatima.dev">hello@fatima.dev ↗</a><div className="links"><button>GitHub</button><button>LinkedIn</button><button>Send a note</button></div></div>}
